name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
  comment-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Comment PR with Branch Name
      uses: actions/github-script@v5
      with:
        script: |
          const branchName = process.env.GITHUB_HEAD_REF;
          const message = `This PR is opened from branch: \`${branchName}\``;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}